os: linux
sudo: false
dist: trusty
language: generic

before_install:
# Docker latest
- curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
- sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
- sudo apt-get update
- sudo apt-get -y install docker-ce

# Docker Compose 1.21.1
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.21.1/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin

script:
- bin/build.sh latest
- bin/test.sh

deploy:
# Push Docker image
- provider: script
  skip_cleanup: true
  script: bin/push.sh ridibooks/ridiselect-apache-base ${TRAVIS_TAG}
  on:
    tags: true
